pool:
  name: Default
  demands: sh

steps:
- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  displayName: 'Installing AWS CLI and required tools'
  inputs:
    awsCredentials: 'AWS-Connection-1'
    regionName: 'us-east-1'
    scriptType: inline
    inlineScript: |
     echo "Install python3.6"
     sudo add-apt-repository ppa:jonathonf/python-3.6
     sudo apt-get update
     sudo apt-get install python3.6
     echo "Installing pip"
     sudo apt install python3-pip
     echo "Installing nodejs"
     curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
     sudo apt-get install -y nodejs
     echo "Installing Serverless"
     sudo npm install -g serverless
     pwd
     ls
     echo "Installing required serverless plugins"
     sudo npm install 
     #pip install -r requirements.txt
     #sudo serverless package --stage dev --package stage-artifacts
     echo "Configuring Credentials for serverless"
     sudo serverless config credentials --provider aws --key  $AWS_ACCESS_KEY_ID --secret  $AWS_SECRET_ACCESS_KEY
     

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  displayName: 'Deploying 1 solution'
  inputs:
    awsCredentials: 'AWS-Connection-1'
    regionName: 'us-east-1'
    scriptType: inline
    inlineScript: |
     echo  "getting serverless info"
     sudo serverless info
     echo  "deploying serverless"
     sudo  serverless deploy -v
